import re

# 需要测试的API和对应的测试用例模板
missing_tests = {
    'button': {
        'getText': "{ name: 'getText', target: 't_button', args: null, verify: function(res) { return typeof res === 'string'; } }",
    },
    'canvas': {
        'addMessageListener': "{ name: 'addMessageListener', target: null, args: [function(){}], verify: function(res) { return res === true; } }",
        'bringToFront': "{ name: 'bringToFront', target: 't_label', args: null, verify: function(res) { return res === true; } }",
        'getPosition': "{ name: 'getPosition', target: 't_label', args: null, verify: function(res) { return res && typeof res.x === 'number'; } }",
        'getSize': "{ name: 'getSize', target: 't_label', args: null, verify: function(res) { return res && typeof res.width === 'number'; } }",
        'getTitleBarTitle': "{ name: 'getTitleBarTitle', target: null, args: null, verify: function(res) { return typeof res === 'string'; } }",
        'move': "{ name: 'move', target: 't_label', args: [50, 50], verify: function(res) { return res === true; } }",
        'parse': "{ name: 'parse', target: null, args: ['[OK]'], verify: function(res) { return typeof res === 'string'; } }",
        'removeMessageListener': "{ name: 'removeMessageListener', target: null, args: [function(){}], verify: function(res) { return res === true; } }",
        'sendMessage': "{ name: 'sendMessage', target: null, args: ['test', 'button', 'click', 't_button', {}], verify: function(res) { return typeof res === 'string'; } }",
        'sendToBack': "{ name: 'sendToBack', target: 't_label', args: null, verify: function(res) { return res === true; } }",
        'setSize': "{ name: 'setSize', target: 't_label', args: [150, 50], verify: function(res) { return res === true; } }",
        'setTitleBarTitle': "{ name: 'setTitleBarTitle', target: null, args: ['测试标题'], verify: function(res) { return typeof res === 'string'; } }",
        'setZIndex': "{ name: 'setZIndex', target: 't_label', args: [99], verify: function(res) { return res === true; } }",
        'showNotification': "{ name: 'showNotification', target: null, args: [{title:'测试', text:'内容'}], verify: function(res) { return res === true; } }",
        'testReturn': "{ name: 'testReturn', target: null, args: null, verify: function(res) { return res !== undefined; } }",
        'toText': "{ name: 'toText', target: null, args: ['[OK]'], verify: function(res) { return typeof res === 'string'; } }",
    },
    'cardBox': {
        'collapseCard': "{ name: 'collapseCard', target: 't_card', args: null, verify: function(res) { return res === true; } }",
        'expandCard': "{ name: 'expandCard', target: 't_card', args: null, verify: function(res) { return res === true; } }",
        'getCardTitle': "{ name: 'getCardTitle', target: 't_card', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'hideCardHeader': "{ name: 'hideCardHeader', target: 't_card', args: null, verify: function(res) { return res === true; } }",
        'isCardCollapsed': "{ name: 'isCardCollapsed', target: 't_card', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'isCardHeaderVisible': "{ name: 'isCardHeaderVisible', target: 't_card', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'isCollapseButtonVisible': "{ name: 'isCollapseButtonVisible', target: 't_card', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'showCardHeader': "{ name: 'showCardHeader', target: 't_card', args: null, verify: function(res) { return res === true; } }",
    },
    'checkbox': {
        'getChecked': "{ name: 'getChecked', target: 't_checkbox', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'getLabel': "{ name: 'getLabel', target: 't_checkbox', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setLabel': "{ name: 'setLabel', target: 't_checkbox', args: ['新标签'], verify: function(res) { return res === true; } }",
    },
    'comboBox': {
        'addItem': "{ name: 'addItem', target: 't_combo', args: ['新选项', 'new'], verify: function(res) { return res === true; } }",
        'clearItems': "{ name: 'clearItems', target: 't_combo', args: null, verify: function(res) { return res === true; } }",
        'getIndex': "{ name: 'getIndex', target: 't_combo', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'getItemCount': "{ name: 'getItemCount', target: 't_combo', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'getText': "{ name: 'getText', target: 't_combo', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'getValue': "{ name: 'getValue', target: 't_combo', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'removeItem': "{ name: 'removeItem', target: 't_combo', args: [0], verify: function(res) { return res === true; } }",
        'setIndex': "{ name: 'setIndex', target: 't_combo', args: [0], verify: function(res) { return res === true; } }",
    },
    'contextMenu': {
        'getItems': "{ name: 'getItems', target: null, args: null, verify: function(res) { return res === null || Array.isArray(res); } }",
        'show': "{ name: 'show', target: null, args: null, verify: function(res) { return res === true; } }",
    },
    'dataGrid': {
        'addRow': "{ name: 'addRow', target: 't_datagrid', args: [{id:'new1', cells:{name:'新增', age:30, city:'北京'}}], verify: function(res) { return res === true; } }",
        'checkAll': "{ name: 'checkAll', target: 't_datagrid', args: null, verify: function(res) { return res === true; } }",
        'clearRows': "{ name: 'clearRows', target: 't_datagrid', args: null, verify: function(res) { return res === true; } }",
        'deselectRow': "{ name: 'deselectRow', target: 't_datagrid', args: [0], verify: function(res) { return res === true; } }",
        'disableCellEdit': "{ name: 'disableCellEdit', target: 't_datagrid', args: [0], verify: function(res) { return res === true; } }",
        'disableGlobalEdit': "{ name: 'disableGlobalEdit', target: 't_datagrid', args: null, verify: function(res) { return res === true; } }",
        'enableGlobalEdit': "{ name: 'enableGlobalEdit', target: 't_datagrid', args: null, verify: function(res) { return res === true; } }",
        'getAlwaysShowSelection': "{ name: 'getAlwaysShowSelection', target: 't_datagrid', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'getCellValueByIndex': "{ name: 'getCellValueByIndex', target: 't_datagrid', args: [0, 1], verify: function(res) { return typeof res === 'string'; } }",
        'getCheckedRows': "{ name: 'getCheckedRows', target: 't_datagrid', args: null, verify: function(res) { return Array.isArray(res); } }",
        'getHighlightedRow': "{ name: 'getHighlightedRow', target: 't_datagrid', args: null, verify: function(res) { return res !== undefined; } }",
        'getRowChecked': "{ name: 'getRowChecked', target: 't_datagrid', args: [0], verify: function(res) { return typeof res === 'boolean'; } }",
        'getRowData': "{ name: 'getRowData', target: 't_datagrid', args: [0], verify: function(res) { return res !== undefined; } }",
        'isCellEditable': "{ name: 'isCellEditable', target: 't_datagrid', args: [0], verify: function(res) { return typeof res === 'boolean'; } }",
        'isGlobalEditEnabled': "{ name: 'isGlobalEditEnabled', target: 't_datagrid', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'isRowChecked': "{ name: 'isRowChecked', target: 't_datagrid', args: [0], verify: function(res) { return typeof res === 'boolean'; } }",
        'removeRow': "{ name: 'removeRow', target: 't_datagrid', args: [0], verify: function(res) { return res === true; } }",
        'selectRow': "{ name: 'selectRow', target: 't_datagrid', args: [0], verify: function(res) { return res === true; } }",
        'setAlwaysShowSelection': "{ name: 'setAlwaysShowSelection', target: 't_datagrid', args: [true], verify: function(res) { return res === true; } }",
        'setCellValue': "{ name: 'setCellValue', api: 'setCellValue', target: 't_datagrid', args: [0, 'name', '测试值'], verify: function(res) { return res === true; } }",
        'setCellValueByIndex': "{ name: 'setCellValueByIndex', target: 't_datagrid', args: [0, 1, '测试'], verify: function(res) { return res === true; } }",
        'setRowChecked': "{ name: 'setRowChecked', target: 't_datagrid', args: [0, true], verify: function(res) { return res === true; } }",
        'setRowData': "{ name: 'setRowData', target: 't_datagrid', args: [0, {cells:{name:'修改', age:25, city:'杭州'}}], verify: function(res) { return res === true; } }",
        'showRowCheckbox': "{ name: 'showRowCheckbox', target: 't_datagrid', args: [true], verify: function(res) { return res === true; } }",
        'uncheckAll': "{ name: 'uncheckAll', target: 't_datagrid', args: null, verify: function(res) { return res === true; } }",
    },
    'dateTimePicker': {
        'getValue': "{ name: 'getValue', target: 't_datetime', args: null, verify: function(res) { return typeof res === 'string'; } }",
    },
    'hyperLink': {
        'getHref': "{ name: 'getHref', target: 't_link', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'getText': "{ name: 'getText', target: 't_link', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setHref': "{ name: 'setHref', target: 't_link', args: ['https://test.com'], verify: function(res) { return res === true; } }",
    },
    'iconButton': {
        'getIconHtml': "{ name: 'getIconHtml', target: 't_iconbtn', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setIconHtml': "{ name: 'setIconHtml', target: 't_iconbtn', args: ['[OK]'], verify: function(res) { return res === true; } }",
    },
    'imageBox': {
        'getFit': "{ name: 'getFit', target: 't_imagebox', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setFit': "{ name: 'setFit', target: 't_imagebox', args: ['cover'], verify: function(res) { return res === true; } }",
    },
    'input': {
        'getPlaceholder': "{ name: 'getPlaceholder', target: 't_input', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'getValue': "{ name: 'getValue', target: 't_input', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setPlaceholder': "{ name: 'setPlaceholder', target: 't_input', args: ['新提示'], verify: function(res) { return res === true; } }",
    },
    'inputBox': {
        'hide': "{ name: 'hide', target: null, args: null, verify: function(res) { return res === true; } }",
        'show': "{ name: 'show', target: null, args: null, verify: function(res) { return res === true; } }",
    },
    'label': {
        'getText': "{ name: 'getText', target: 't_label', args: null, verify: function(res) { return typeof res === 'string'; } }",
    },
    'listBox': {
        'checkAll': "{ name: 'checkAll', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'clearItems': "{ name: 'clearItems', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'deleteSelected': "{ name: 'deleteSelected', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'deselectItem': "{ name: 'deselectItem', target: 't_listbox', args: [0], verify: function(res) { return res === true; } }",
        'disableDblClickEdit': "{ name: 'disableDblClickEdit', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'enableDblClickEdit': "{ name: 'enableDblClickEdit', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'getAlwaysShowSelection': "{ name: 'getAlwaysShowSelection', target: 't_listbox', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'getCheckedItems': "{ name: 'getCheckedItems', target: 't_listbox', args: null, verify: function(res) { return Array.isArray(res); } }",
        'getHighlightedItem': "{ name: 'getHighlightedItem', target: 't_listbox', args: null, verify: function(res) { return res !== null; } }",
        'getItemChecked': "{ name: 'getItemChecked', target: 't_listbox', args: [0], verify: function(res) { return typeof res === 'boolean'; } }",
        'getItemCount': "{ name: 'getItemCount', target: 't_listbox', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'getItemText': "{ name: 'getItemText', target: 't_listbox', args: [0], verify: function(res) { return typeof res === 'string'; } }",
        'getSelectedItemId': "{ name: 'getSelectedItemId', target: 't_listbox', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'isItemChecked': "{ name: 'isItemChecked', target: 't_listbox', args: [0], verify: function(res) { return typeof res === 'boolean'; } }",
        'removeItem': "{ name: 'removeItem', target: 't_listbox', args: [0], verify: function(res) { return res === true; } }",
        'selectAll': "{ name: 'selectAll', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'selectItem': "{ name: 'selectItem', target: 't_listbox', args: [0], verify: function(res) { return res === true; } }",
        'setAlwaysShowSelection': "{ name: 'setAlwaysShowSelection', target: 't_listbox', args: [true], verify: function(res) { return res === true; } }",
        'setItemChecked': "{ name: 'setItemChecked', target: 't_listbox', args: [0, true], verify: function(res) { return res === true; } }",
        'setItemText': "{ name: 'setItemText', target: 't_listbox', args: [0, '修改文本'], verify: function(res) { return res === true; } }",
        'showCheckbox': "{ name: 'showCheckbox', target: 't_listbox', args: [true], verify: function(res) { return res === true; } }",
        'toggleAll': "{ name: 'toggleAll', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
        'uncheckAll': "{ name: 'uncheckAll', target: 't_listbox', args: null, verify: function(res) { return res === true; } }",
    },
    'logOutput': {
        'addHtmlLog': "{ name: 'addHtmlLog', target: 't_log', args: ['<b>加粗</b>'], verify: function(res) { return res === true; } }",
        'clearLog': "{ name: 'clearLog', target: 't_log', args: null, verify: function(res) { return res === true; } }",
        'getLogCount': "{ name: 'getLogCount', target: 't_log', args: null, verify: function(res) { return typeof res === 'number'; } }",
    },
    'messageBox': {
        'hide': "{ name: 'hide', target: null, args: null, verify: function(res) { return res === true; } }",
        'show': "{ name: 'show', target: null, args: null, verify: function(res) { return res === true; } }",
    },
    'progressBar': {
        'decrement': "{ name: 'decrement', target: 't_progress', args: [10], verify: function(res) { return res === true; } }",
        'disableClick': "{ name: 'disableClick', target: 't_progress', args: null, verify: function(res) { return res === true; } }",
        'enableClick': "{ name: 'enableClick', target: 't_progress', args: null, verify: function(res) { return res === true; } }",
        'getValue': "{ name: 'getValue', target: 't_progress', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'increment': "{ name: 'increment', target: 't_progress', args: [10], verify: function(res) { return res === true; } }",
        'setRange': "{ name: 'setRange', target: 't_progress', args: [0, 100], verify: function(res) { return res === true; } }",
    },
    'public': {
        'addMessageListener': "{ name: 'addMessageListener', target: null, args: [function(){}], verify: function(res) { return res === true; } }",
        'bringToFront': "{ name: 'bringToFront', target: 't_label', args: null, verify: function(res) { return res === true; } }",
        'focus': "{ name: 'focus', target: 't_input', args: null, verify: function(res) { return res === true; } }",
        'getBlockContextMenu': "{ name: 'getBlockContextMenu', target: null, args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'getChecked': "{ name: 'getChecked', target: 't_checkbox', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'getIdByName': "{ name: 'getIdByName', target: null, args: ['测试按钮'], verify: function(res) { return res === 't_button'; } }",
        'getInfoById': "{ name: 'getInfoById', target: null, args: ['t_button'], verify: function(res) { return res !== null; } }",
        'getPosition': "{ name: 'getPosition', target: 't_label', args: null, verify: function(res) { return res && typeof res.x === 'number'; } }",
        'getSize': "{ name: 'getSize', target: 't_label', args: null, verify: function(res) { return res && typeof res.width === 'number'; } }",
        'getTitleBarTitle': "{ name: 'getTitleBarTitle', target: null, args: null, verify: function(res) { return typeof res === 'string'; } }",
        'getValue': "{ name: 'getValue', target: 't_input', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'hide': "{ name: 'hide', target: 't_label', args: null, verify: function(res) { return res === true; } }",
        'isEnabled': "{ name: 'isEnabled', target: 't_input', args: null, verify: function(res) { return res === true; } }",
        'isVisible': "{ name: 'isVisible', target: 't_label', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'move': "{ name: 'move', target: 't_label', args: [20, 20], verify: function(res) { return res === true; } }",
        'parse': "{ name: 'parse', target: null, args: ['[OK]'], verify: function(res) { return typeof res === 'string'; } }",
        'sendMessage': "{ name: 'sendMessage', target: null, args: ['test', 'button', 'click', 't_button', {}], verify: function(res) { return typeof res === 'string'; } }",
        'sendToBack': "{ name: 'sendToBack', target: 't_label', args: null, verify: function(res) { return res === true; } }",
        'setBlockContextMenu': "{ name: 'setBlockContextMenu', target: null, args: [false], verify: function(res) { return res === true; } }",
        'setChecked': "{ name: 'setChecked', target: 't_checkbox', args: [true], verify: function(res) { return res === true; } }",
        'setEnabled': "{ name: 'setEnabled', target: 't_input', args: [true], verify: function(res) { return res === true; } }",
        'setFixedCanvasSize': "{ name: 'setFixedCanvasSize', target: null, args: [false], verify: function(res) { return res === true; } }",
        'setSize': "{ name: 'setSize', target: 't_label', args: [120, 40], verify: function(res) { return res === true; } }",
        'setStyle': "{ name: 'setStyle', target: 't_label', args: [{backgroundColor:'#f0f0f0'}], verify: function(res) { return res === true; } }",
        'setTitleBarTitle': "{ name: 'setTitleBarTitle', target: null, args: ['新标题'], verify: function(res) { return typeof res === 'string'; } }",
        'setZIndex': "{ name: 'setZIndex', target: 't_label', args: [10], verify: function(res) { return res === true; } }",
        'show': "{ name: 'show', target: 't_label', args: null, verify: function(res) { return res === true; } }",
        'showNotification': "{ name: 'showNotification', target: null, args: [{title:'测试', text:'内容'}], verify: function(res) { return res === true; } }",
        'testReturn': "{ name: 'testReturn', target: null, args: null, verify: function(res) { return res !== undefined; } }",
        'toText': "{ name: 'toText', target: null, args: ['[OK]'], verify: function(res) { return typeof res === 'string'; } }",
        'toggle': "{ name: 'toggle', target: 't_label', args: null, verify: function(res) { return res === true; } }",
    },
    'radioGroup': {
        'addOption': "{ name: 'addOption', target: 't_radiogroup', args: ['新选项', 'new_opt'], verify: function(res) { return res === true; } }",
        'getIndex': "{ name: 'getIndex', target: 't_radiogroup', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'getValue': "{ name: 'getValue', target: 't_radiogroup', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setIndex': "{ name: 'setIndex', target: 't_radiogroup', args: [0], verify: function(res) { return res === true; } }",
    },
    'switchToggle': {
        'getChecked': "{ name: 'getChecked', target: 't_switch', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
    },
    'tabContainer': {
        'addTab': "{ name: 'addTab', target: 't_tabs', args: ['newtab', '新标签'], verify: function(res) { return typeof res === 'string'; } }",
        'getActiveTab': "{ name: 'getActiveTab', target: 't_tabs', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'getActiveTabIndex': "{ name: 'getActiveTabIndex', target: 't_tabs', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'getTabCount': "{ name: 'getTabCount', target: 't_tabs', args: null, verify: function(res) { return typeof res === 'number'; } }",
        'getTabHeaderVisible': "{ name: 'getTabHeaderVisible', target: 't_tabs', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'removeTab': "{ name: 'removeTab', target: 't_tabs', args: ['newtab'], verify: function(res) { return res === true; } }",
        'renameTab': "{ name: 'renameTab', target: 't_tabs', args: ['tab1', '重命名'], verify: function(res) { return res === true; } }",
    },
    'textarea': {
        'getPlaceholder': "{ name: 'getPlaceholder', target: 't_textarea', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'getValue': "{ name: 'getValue', target: 't_textarea', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'setPlaceholder': "{ name: 'setPlaceholder', target: 't_textarea', args: ['请输入'], verify: function(res) { return res === true; } }",
    },
    'tooltip': {
        'getConfig': "{ name: 'getConfig', target: null, args: null, verify: function(res) { return res === null || typeof res === 'object'; } }",
        'show': "{ name: 'show', target: null, args: null, verify: function(res) { return res === true; } }",
    },
    'treeView': {
        'checkAll': "{ name: 'checkAll', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'clearSelection': "{ name: 'clearSelection', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'clearTree': "{ name: 'clearTree', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'collapseAll': "{ name: 'collapseAll', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'collapseNode': "{ name: 'collapseNode', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'deselectNode': "{ name: 'deselectNode', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'disableAllEdit': "{ name: 'disableAllEdit', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'disableNodeEdit': "{ name: 'disableNodeEdit', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'enableAllEdit': "{ name: 'enableAllEdit', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'enableNodeEdit': "{ name: 'enableNodeEdit', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'expandAll': "{ name: 'expandAll', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'expandNode': "{ name: 'expandNode', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'getAlwaysShowSelection': "{ name: 'getAlwaysShowSelection', target: 't_tree', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'getCheckedNodes': "{ name: 'getCheckedNodes', target: 't_tree', args: null, verify: function(res) { return Array.isArray(res); } }",
        'getHighlightedNode': "{ name: 'getHighlightedNode', target: 't_tree', args: null, verify: function(res) { return res !== null; } }",
        'getNodeLevel': "{ name: 'getNodeLevel', target: 't_tree', args: ['n1'], verify: function(res) { return typeof res === 'number'; } }",
        'getSelectedNode': "{ name: 'getSelectedNode', target: 't_tree', args: null, verify: function(res) { return typeof res === 'string'; } }",
        'isAllEditEnabled': "{ name: 'isAllEditEnabled', target: 't_tree', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'isCheckboxVisible': "{ name: 'isCheckboxVisible', target: 't_tree', args: null, verify: function(res) { return typeof res === 'boolean'; } }",
        'isNodeChecked': "{ name: 'isNodeChecked', target: 't_tree', args: ['n1'], verify: function(res) { return typeof res === 'boolean'; } }",
        'removeNode': "{ name: 'removeNode', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'selectNode': "{ name: 'selectNode', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'setAlwaysShowSelection': "{ name: 'setAlwaysShowSelection', target: 't_tree', args: [true], verify: function(res) { return res === true; } }",
        'setNodeChecked': "{ name: 'setNodeChecked', target: 't_tree', args: ['n1', true], verify: function(res) { return res === true; } }",
        'showCheckbox': "{ name: 'showCheckbox', target: 't_tree', args: [true], verify: function(res) { return res === true; } }",
        'toggleNode': "{ name: 'toggleNode', target: 't_tree', args: ['n1'], verify: function(res) { return res === true; } }",
        'uncheckAll': "{ name: 'uncheckAll', target: 't_tree', args: null, verify: function(res) { return res === true; } }",
        'updateNode': "{ name: 'updateNode', target: 't_tree', args: ['n1', '新名称'], verify: function(res) { return res === true; } }",
    },
}

# 生成测试代码
output = []
for module, tests in sorted(missing_tests.items()):
    output.append(f"\n    // ===== {module} 补充测试 =====")
    output.append(f"    {{")
    output.append(f"      module: '{module}',")
    output.append(f"      title: '{module} API (补充)',")
    output.append(f"      tests: [")
    
    for api_name, test_code in sorted(tests.items()):
        output.append(f"        {test_code},")
    
    output.append(f"      ]")
    output.append(f"    }},")

print('\n'.join(output))
print(f"\n总计: {sum(len(v) for v in missing_tests.values())} 个测试用例")
